<?php

namespace Upendo\Repository;

use Doctrine\ORM\EntityRepository;
use Upendo\Entity\User;

/**
 * ProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConversationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getConversationForUsers($userOne, $userTwo)
    {
        $qb = $this->createQueryBuilder('c');

        $qb
            ->select('c', 'userOne', 'userTwo')
            ->leftJoin('c.users', 'userOne')
            ->leftJoin('c.users', 'userTwo')
        ;

        $qb
            ->where('userOne.id = :user_one')
            ->andWhere('userTwo.id = :user_two')
            ->setParameters([
                'user_one' => ($userOne instanceof User ? $userOne->getId() : $userOne),
                'user_two' => ($userTwo instanceof User ? $userTwo->getId() : $userTwo),
            ])
        ;

        return $qb->getQuery()->execute();
    }
}
