<?php

namespace Upendo\Repository;

use Doctrine\ORM\EntityRepository;
use Upendo\Entity\User;

/**
 * ProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DailyProfileRepository extends EntityRepository
{
    public function getDailyProfile(User $user)
    {
        $qb = $this->createQueryBuilder('dp');

        $today = new \DateTime();
        $today = $today->format('Y-m-d');

        $qb
            ->where('dp.date = :date')
            ->andWhere('dp.userOne = :user OR dp.userTwo = :user')
            ->setParameters([
                'date' => $today,
                'user' => $user
            ])
        ;

        return $qb->getQuery()->execute();
    }
}
