version: '3.3'

services:
    client:
        env_file: .env
        build:
            context: ./client-web/docker
        volumes:
            - ./client-web/:/app/
        ports:
            - 4001:4001
        command: npm run start
        labels:
            - "traefik.backend=client.upendo"
            - "traefik.frontend.rule=Host:upendo.localhost"
            - "traefik.port=4001"
            - "traefik.frontend.passHostHeader=true"

    nginx:
        user: ikimea
        image: registry.containers.ovh.net/upendo/nginx
        labels:
           - "traefik.backend=api.upendo"
           - "traefik.frontend.rule=Host:api.upendo.localhost"
           - "traefik.port=80"
           - "traefik.frontend.passHostHeader=true"
           - "traefik.backend.loadbalancer.method=drr"
        depends_on:
           - php
        volumes:
           - ./api/public:/opt/project/public
           - ./api/docker/nginx/config/api.conf:/etc/nginx/conf.d/default.conf
           - ./var/logs/nginx/:/var/log/nginx

    assets:
        user: ikimea
        image: registry.containers.ovh.net/upendo/nginx
        labels:
           - "traefik.backend=assets.upendo"
           - "traefik.frontend.rule=Host:assets.api.upendo.localhost"
           - "traefik.port=80"
           - "traefik.frontend.passHostHeader=true"
           - "traefik.backend.loadbalancer.method=drr"
        volumes:
           - ./api/public:/opt/project/public
           - ./api/docker/nginx/config/assets.conf:/etc/nginx/conf.d/default.conf
           - ./var/logs/nginx/:/var/log/nginx

    php:
        user: ikimea
        image: registry.containers.ovh.net/upendo/php
        env_file: ["api/docker/.env.dev", ".env"]
        depends_on:
            - database
        volumes:
            - ./api/:/opt/project/
        labels:
            - "traefik.enable=false"

    database:
        image: postgres:9.6
        env_file: ["api/docker/.env.dev", ".env"]
        volumes:
            - ./docker/database/:/var/lib/postgresql/data/
        labels:
            - "traefik.enable=false"

networks:
  default:
    external:
      name: devtools
