version: '2'

services:
    upendo_nginx:
        image: ikimea/nginx
        labels:
           - "traefik.backend=upendo_$CI_BUILD_REF_NAME"
           - "traefik.frontend.rule=Host:$CI_BUILD_REF_NAME.upendo.stage.ikimea.io"
           - "traefik.port=80"
           - "traefik.frontend.passHostHeader=true"
           - "traefik.backend.loadbalancer.method=drr"
        volumes_from:
            - upendo_php
        volumes:
           - ./docker/nginx/config/nginx.conf:/etc/nginx/conf.d/default.conf
           - ./:/opt/project

    upendo_php:
        build:
            context: .
            dockerfile: docker/app/Dockerfile
            args:
                GID: 3000
                UID: 3000
        depends_on:
            - upendo_redis
            - upendo_rabbitmq
            - upendo_database
        volumes:
            - ./docker/nginx/config/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./:/opt/project
        environment:
            - LOGSTASH_HOST=logstash.localhost
            - SYMFONY_ENV=dev
            - SECRET=abf4a4ed3b7a4e7094e4a0949d12b234
            - CORS_ALLOW_ORIGIN=http://$CI_BUILD_REF_NAME}.upendo.stage.ikimea.io
            - LOGSTASH_PORT=5044
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=upendo_database
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=ikimea_upendo
            - REDIS_HOST=upendo_redis
            - RABBITMQ_PORT=5672
            - RABBITMQ_HOST=upendo_rabbitmq
            - RABBITMQ_LOGIN=guest
            - RABBITMQ_PASSWORD=guest
        labels:
            - "traefik.enable=false"

    upendo_database:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=ikimea_upendo
        labels:
            - "traefik.enable=false"

    upendo_rabbitmq:
        image: rabbitmq:3.6-management
        labels:
            - "traefik.backend=upendo_rabbitmq_$CI_BUILD_REF_NAME"
            - "traefik.frontend.rule=Host:rabbitmq.$CI_BUILD_REF_NAME.upendo.stage.ikimea.io"
            - "traefik.port=80"
            - "traefik.frontend.passHostHeader=true"
            - "traefik.backend.loadbalancer.method=drr"
        environment:
            - "RABBITMQ_DEFAULT_USER=guest"
            - "RABBITMQ_DEFAULT_PASS=guest"

    upendo_redis:
        image: redis:3.0.7
        labels:
            - "traefik.enable=false"

networks:
  default:
    external:
      name: devtools
