version: '2'

services:
    upendo_nginx:
        user: ikimea
        image: ikimea/nginx
        labels:
           - "traefik.backend=upendo"
           - "traefik.frontend.rule=Host:api.${SITE_HOST}"
           - "traefik.port=80"
           - "traefik.frontend.passHostHeader=true"
           - "traefik.backend.loadbalancer.method=drr"
        volumes_from:
           - upendo_php
        volumes:
           - ./:/opt/project
           - ./docker/nginx/config/nginx.conf:/etc/nginx/conf.d/default.conf
           - ./var/logs/nginx/:/var/log/nginx
        environment:
           - NGINX_PHP_FPM=${NGINX_PHP_FPM}

    upendo_php:
        user: ikimea
        build:
            context: .
            dockerfile: docker/app/Dockerfile
            args:
                GID: ${GID}
                UID: ${UID}
                LIB_EXTENSIONS: xdebug
        env_file: .env
        depends_on:
            - upendo_database
        volumes:
            - ./:/opt/project
        labels:
            - "traefik.enable=false"

    upendo_database:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        env_file: .env
        labels:
            - "traefik.enable=false"

networks:
  default:
    external:
      name: devtools
