version: '3.3'

services:
    php:
        user: ikimea
        build:
            context: .
            dockerfile: api/docker/php/Dockerfile
            args:
                GID: 3000
                UID: 3000
        depends_on:
            - rabbitmq
            - redis
            - database
        env_file: ./api/docker/php/.env.ci
        volumes:
            - ~/.composer:/home/ikimea/.composer
            - .:/opt/project

    database:
        image: postgres:10.0
        env_file: ./api/docker/php/.env.ci
        environment:
            - POSTGRES_USER=upendo
            - POSTGRES_PASSWORD=azerty123
            - POSTGRES_DB=upendo

    rabbitmq:
        image: rabbitmq:3.6-management

    redis:
        image: redis:3.0
