version: '3'

services:
    upendo_client:
        env_file: .env
        build:
            context: ./docker/client-web/
        volumes:
            - ./client-web/:/app/
        ports:
            - 4001:4001
        command: npm run start
        labels:
            - "traefik.backend=upendo_client"
            - "traefik.frontend.rule=Host:${SITE_HOST}"
            - "traefik.port=4001"
            - "traefik.frontend.passHostHeader=true"

    upendo_nginx:
        user: ikimea
        image: ikimea/nginx
        labels:
           - "traefik.backend=api.upendo"
           - "traefik.frontend.rule=Host:api.${SITE_HOST}"
           - "traefik.port=80"
           - "traefik.frontend.passHostHeader=true"
           - "traefik.backend.loadbalancer.method=drr"
        depends_on:
           - upendo_php
        volumes:
           - ./my-backend/:/opt/project/
           - ./docker/nginx/config/nginx.conf:/etc/nginx/conf.d/default.conf
           - ./var/logs/nginx/:/var/log/nginx
        environment:
           - NGINX_PHP_FPM=${NGINX_PHP_FPM}

    upendo_assets:
        user: ikimea
        image: ikimea/nginx
        labels:
           - "traefik.backend=assets.upendo"
           - "traefik.frontend.rule=Host:assets.${SITE_HOST}"
           - "traefik.port=80"
           - "traefik.frontend.passHostHeader=true"
           - "traefik.backend.loadbalancer.method=drr"
        volumes:
           - ./my-backend/:/opt/project/
           - ./docker/nginx_assets/config/nginx.conf:/etc/nginx/conf.d/default.conf
           - ./var/logs/nginx_assets/:/var/log/nginx
        environment:
           - NGINX_PHP_FPM=${NGINX_PHP_FPM}

    upendo_php:
        user: ikimea
        build:
            context: ./docker/php/
            args:
                GID: ${GID}
                UID: ${UID}
                LIB_EXTENSIONS: xdebug
        env_file: .env
        depends_on:
            - upendo_database
        volumes:
            - ./my-backend/:/opt/project/
        labels:
            - "traefik.enable=false"

    upendo_database:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        env_file: .env
        volumes:
            - ./docker/database/:/var/lib/postgresql/data/
        labels:
            - "traefik.enable=false"

networks:
  default:
    external:
      name: devtools
