# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.security.user_provider:
        class: AppBundle\Security\UserProvider
        arguments: [ '@doctrine.orm.entity_manager' ]
    app.security.api_key_authenticator:
        class: AppBundle\Security\ApiKeyAuthenticator
    app.security.success_handler:
        class: AppBundle\Security\SuccessHandler
        arguments: [ '@doctrine.orm.entity_manager' ]
    app.listener.password_encoder:
        class: AppBundle\EventListener\PasswordEncoder
        arguments: [ '@security.password_encoder' ]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            
    # api platform filters
    # users.list_filter:
        # parent:    'api_platform.doctrine.orm.search_filter'
        # arguments: [ { gender: 'exact', profile.searchingGender: 'exact',  } ]
        # tags:      [ { name: 'api_platform.filter', id: 'users.list' } ]
    
    'AppBundle\Filter\UsersFilter':
        class: 'AppBundle\Filter\UsersFilter'
        autowire: true
        arguments: [ '@security.token_storage', '@doctrine', '@request_stack', '@logger', { by: 'criteria' } ]
        tags: [ { name: 'api_platform.filter', id: 'users_filter' } ]

    # doctrine subscribers
    'AppBundle\EventSubscriber\DoctrineEventSubscriber':
        arguments: [ '@security.token_storage', '@request_stack', "%profiles_uploads_short_path%" ]
        tags:
            - { name: doctrine.event_subscriber, connection: default }
    