api:
    resource: '.'
    type:     'api_platform'

# app:
    # resource: '@AppBundle/Action/'
    # type:     'annotation'

api_login:
    path: /login
    defaults:
        _controller: Upendo\Controller\SecurityController::loginAction

test_action:
    path: /debug/test
    defaults:
        _controller: Upendo\Controller\SecurityController::testAction

file_upload:
    path: /upload
    defaults:
        _controller: Upendo\Controller\FileController::uploadAction

daily_profile:
    path: /daily_profile
    defaults:
        _controller: Upendo\Controller\UserController::dailyProfileAction

contacts_list:
    path: /contacts_list
    defaults:
        _controller: Upendo\Controller\UserController::getContactsAction

debug:
    path: /debug
    defaults:
        _controller: Upendo\Controller\DebugController::debugAction