api:
    resource: '.'
    type:     'api_platform'

# app:
    # resource: '@AppBundle/Action/'
    # type:     'annotation'

api_login:
    path: /login
    defaults:
        _controller: Upendo\Controller\SecurityController::loginAction

test_action:
    path: /debug/test
    defaults:
        _controller: Upendo\Controller\SecurityController::testAction

file_upload:
    path: /upload
    defaults:
        _controller: Upendo\Controller\FileController::uploadAction
