# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Upendo\Entity\User: bcrypt

    providers:
        custom_user_provider:
            id: app.security.user_provider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false                

        debug:
              pattern: ^/debug
              anonymous: ~

        api:
            pattern: ^/
            stateless: true
            simple_preauth:
                authenticator: app.security.api_key_authenticator
            provider: custom_user_provider
            json_login:
                check_path: api_login
                success_handler: app.security.success_handler
                
        main:
            anonymous: ~
        
    access_control:
        - { path: ^/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/daily_profile, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/users, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: [POST] }
        - { path: ^/*, roles: ROLE_USER }
