services:
    app.security.user_provider:
        class: Upendo\Security\UserProvider
        arguments: [ '@doctrine.orm.entity_manager' ]
    app.security.api_key_authenticator:
        class: Upendo\Security\ApiKeyAuthenticator
    app.security.success_handler:
        class: Upendo\Security\SuccessHandler
        arguments: [ '@doctrine.orm.entity_manager' ]
    app.listener.password_encoder:
        class: Upendo\EventListener\PasswordEncoder
        arguments: [ '@security.password_encoder' ]
        tags:
            - { name: doctrine.event_listener, event: prePersist }


#    ManagerRegistry $managerRegistry, RequestStack $requestStack, LoggerInterface $logger = null, array $properties = null
    'Upendo\Filter\UsersFilter':
#        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ '@doctrine', '@request_stack', '@logger', '@security.token_storage' ]
#        arguments: [ { gender: 'exact', profile.searchingGender: 'exact'} ]
        tags: ['api_platform.filter']
#        calls:
#            - { method: setTokenStorage, arguments: ['@security.token_storage'] }

#        class: 'Upendo\Filter\UsersFilter'
#        parent: 'api_platform.doctrine.orm.search_filter'

#        tags:      [ { name: 'api_platform.filter', id: 'users.list' } ]


    # doctrine subscribers
    'Upendo\EventSubscriber\DoctrineEventSubscriber':
        arguments: [ '@security.token_storage', '@request_stack', "%profiles_uploads_short_path%" ]
        tags:
            - { name: doctrine.event_subscriber, connection: default }
    