imports:
    - { resource: security.yml }
    - { resource: services.yml }

parameters:
    locale: en
    secret: "%env(SECRET)%"

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  snc_redis.session.handler
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_pgsql
        host:     "%env(POSTGRES_HOST)%"
        port:     "%env(POSTGRES_PORT)%"
        dbname:   "%env(POSTGRES_DB)%"
        user:     "%env(POSTGRES_USER)%"
        password: "%env(POSTGRES_PASSWORD)%"
        charset:  UTF8
        server_version: 9.6
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                auto_mapping: true
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    App:
                        type: annotation
                        dir: '%kernel.root_dir%/../src/Entity'
                        prefix: Upendo\Entity
                        alias: Upendo

doctrine_migrations:
    dir_name: '%kernel.root_dir%/../etc/DoctrineMigrations'


# Swiftmailer Configuration
#swiftmailer:
#    transport: "%mailer_transport%"
#    host:      "%mailer_host%"
#    username:  "%mailer_user%"
#    password:  "%mailer_password%"
#    spool:     { type: memory }

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: "redis://%env(REDIS_HOST)%"
            logging: "%kernel.debug%"

        cache:
            type: predis
            alias: cache
            dsn: "redis://%env(REDIS_HOST)%"
            logging: "%kernel.debug%"
        session:
            type: predis
            alias: session
            dsn: "redis://%env(REDIS_HOST)%"
            logging: "%kernel.debug%"
    session:
        client: session

swarrot:
    provider: pecl
    default_connection: rabbitmq
    default_command: swarrot.command.base # Swarrot\SwarrotBundle\Command\SwarrotCommand
    connections:
        general:
            host: "%env(RABBITMQ_HOST)%"
            port: 5672
            login: "%env(RABBITMQ_LOGIN)%"
            password: "%env(RABBITMQ_PASSWORD)%"
            vhost: 'ikimea'

        rabbitmq:
           host: "%env(RABBITMQ_HOST)%"
           port: 5672
           login: "%env(RABBITMQ_LOGIN)%"
           password: "%env(RABBITMQ_PASSWORD)%"
           vhost: 'upendo'

    messages_types:
        generic:
            connection: general
            exchange: generic

doctrine_migrations:
    dir_name: "%%"

api_platform: ~