api:
    resource: '.'
    type:     'api_platform'

# app:
    # resource: '@AppBundle/Action/'
    # type:     'annotation'

api_login:
    path: /login
    defaults:
        _controller: AppBundle:Security:login

